language: ruby
rvm:
- 2.2.5
branches:
  only:
  - master
sudo: false
script:
- bundle exec jekyll build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: gae.json
  project: luecox
before_install:
- openssl aes-256-cbc -K $encrypted_876de92c8423_key -iv $encrypted_876de92c8423_iv
  -in gae.json.enc -out gae.json -d
