application: luecox
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:

- url: /(.*\.(jpg|png|ico))
  mime_type: image/png
  static_files: _site/\1
  upload: _site/(.*\.img)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: _site/\1
  upload: _site/(.*\.js)

- url: /(.*\.css)
  mime_type: text/css
  static_files: _site/\1
  upload: _site/(.*\.css)

- url: /(.*\.(eot|svg|svgz|otf|ttf|woff|woff2))
  static_files: _site/\1
  upload: _site/(.*\.fonts)

- url: /img
  static_dir: _site/img

- url: /fonts
  static_dir: _site/fonts

- url: /(.*)
  script: main.py
